# Generated by Django 3.1 on 2020-08-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25600)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25600)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25600)),
                ('published_date', models.CharField(max_length=25600, null=True)),
                ('average_rating', models.IntegerField(null=True)),
                ('ratings_count', models.IntegerField(null=True)),
                ('thumbnail', models.CharField(max_length=25600, null=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.author')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.category')),
            ],
        ),
    ]
